### ISSUE TITLE
Proxy-pallet: add testing (part 2)

### ISSUE THREAD

**Issue by tlacloc** [hashed-io/hashed-substrate#151]
# TODO

Add testing for 

- [ ] add testing related to changes on #150 
- [ ] add testing related to changes on #149 
- [ ] add testing related to changes on #147

**Comment by didiermis** [comment]
New tickets are:
- #344 
- #345 
- #346 
- #347 
- #348
